### ISSUE TITLE
Norwegian (Norsk) <no-no.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/RadialOmniSeparator#23]
# Localization - ![Norsk][NO] Norwegian (Norsk) <no-no.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: type: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[no-no.cfg] 🗃️

### Translation

* [x] ![Norsk][NO] Norwegian (Norsk) <no-no.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[NO]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/NO.png "Norsk"

this file: © All Rights Reserved by zer0Kerbal

**Comment by tplive** [comment]
I can work on this! 🇳🇴 🥳

**Comment by tplive** [comment]
Some questions:

Is `no-no.cfg` a required filname convention in the software? In Norwegian, we would usually have two different translation, one for `bokmål` and another for `nynorsk`, equating to our two different written forms. They would then be called `no-nb` and `no-nn`, respectively.

Then - It would be helpful with some context for the actual texts, maybe screenshots of how it would appear in the game? I have not played it. 😅 Could that be made available, or should I rather get the game?

**Comment by zer0Kerbal** [comment]
https://wiki.kerbalspaceprogram.com/wiki/Decoupler_and_separator

**Comment by tplive** [comment]
Thanks for the link! I think I understand the context better now, so I have updated the translation.

**Comment by zer0Kerbal** [comment]
> Thanks for the link! I think I understand the context better now, so I have updated the translation.

Excellent. I am researching the other question, just am under the weather a tad. 

And yes, these are radially attached parts that for a lack of a better phrase - are _explosive bolts_.

**Comment by zer0Kerbal** [comment]
I did some digging, there isn't an 'official' (Squad/KSP) Norsk translation - so either one, or rather the most popular (like Mandarin vs. Cantonese) 

The Game should use the dictionary version that the OS is set to.

![image](https://user-images.githubusercontent.com/39887717/196011131-bcb51bcf-d470-4de3-9936-133f9096f7dc.png)
